// Generated by tools/generate_viewmodel_module.py. Do not edit.
//
// Every ViewModel the Dagger factory can build, keyed by class. Hilt discovered
// these by itself; plain Dagger needs the list.
package tf.monochrome.desktop.di

import androidx.lifecycle.ViewModel
import dagger.Binds
import dagger.Module
import dagger.multibindings.IntoMap
import dagger.multibindings.Multibinds

@Module
abstract class ViewModelModule {
    @Multibinds abstract fun plainViewModels(): Map<Class<out ViewModel>, ViewModel>
    @Multibinds abstract fun assistedViewModels(): Map<Class<out ViewModel>, SavedStateVmFactory<*>>

}
