#!/usr/bin/env python3
"""
Writes app/src/main/kotlin/tf/monochrome/desktop/di/ViewModelModule.kt: the
Dagger multibinding map of every ViewModel class in the compiled tree.

Hilt found @HiltViewModel classes by itself; plain Dagger needs each one listed.
This scans the sources for classes annotated @HiltViewModel (the annotation is
kept as a marker) and binds them into the map AppViewModelFactory reads. A
ViewModel whose constructor takes a SavedStateHandle is bound through its
assisted Factory instead (see di/ViewModelFactory.kt), which the class must
declare as `@AssistedFactory interface Factory : SavedStateVmFactory<X>`.

    python3 tools/generate_viewmodel_module.py
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'app', 'src', 'main', 'kotlin', 'tf', 'monochrome', 'desktop')
OUT = os.path.join(SRC, 'di', 'ViewModelModule.kt')

def main():
    plain, assisted = [], []
    for root, _, files in os.walk(SRC):
        for fn in files:
            if not fn.endswith('.kt'):
                continue
            path = os.path.join(root, fn)
            text = open(path, encoding='utf-8').read()
            if '@HiltViewModel' not in text:
                continue
            pkg = re.search(r'^package\s+([\w.]+)', text, re.M).group(1)
            for m in re.finditer(r'@HiltViewModel\s*(?:@\w+(?:\([^)]*\))?\s*)*class\s+(\w+)\s*(?:@\w+\s*)?(?:constructor)?\s*\(([^)]*)\)', text, re.S):
                name, params = m.group(1), m.group(2)
                fq = f'{pkg}.{name}'
                if 'SavedStateHandle' in params:
                    assisted.append(fq)
                else:
                    plain.append(fq)
    plain.sort(); assisted.sort()
    out = ['// Generated by tools/generate_viewmodel_module.py. Do not edit.',
           '//',
           '// Every ViewModel the Dagger factory can build, keyed by class. Hilt discovered',
           '// these by itself; plain Dagger needs the list.',
           'package tf.monochrome.desktop.di',
           '',
           'import androidx.lifecycle.ViewModel',
           'import dagger.Binds',
           'import dagger.Module',
           'import dagger.multibindings.IntoMap',
           'import dagger.multibindings.Multibinds',
           '',
           '@Module',
           'abstract class ViewModelModule {',
           '    @Multibinds abstract fun plainViewModels(): Map<Class<out ViewModel>, ViewModel>',
           '    @Multibinds abstract fun assistedViewModels(): Map<Class<out ViewModel>, SavedStateVmFactory<*>>',
           '']
    for fq in plain:
        simple = fq.rsplit('.', 1)[1]
        out.append(f'    @Binds @IntoMap @ViewModelKey({fq}::class)')
        out.append(f'    abstract fun bind{simple}(vm: {fq}): ViewModel')
        out.append('')
    for fq in assisted:
        simple = fq.rsplit('.', 1)[1]
        out.append(f'    @Binds @IntoMap @ViewModelKey({fq}::class)')
        out.append(f'    abstract fun bind{simple}Factory(factory: {fq}.Factory): SavedStateVmFactory<*>')
        out.append('')
    out.append('}')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    print(f'{len(plain)} plain and {len(assisted)} SavedStateHandle ViewModels bound')

main()
