// Pins every snapin's default parameters to a committed table,
// app/src/test/resources/snapin_defaults.csv, which the Kotlin side checks
// ParamDefs.kt against too (SnapinDefaultsTest). Between them, the value a
// knob shows for an untouched parameter is the value the effect runs with.
//
//   snapin_defaults_test <csv>            check
//   snapin_defaults_test <csv> --write    regenerate after a deliberate change

#include <cstdio>
#include <cstring>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "../dsp_engine.h"

namespace {

constexpr int kTypes = 36;

std::vector<float> nativeDefaults(int type) {
    DspEngine e(48000, 512);
    e.addPlugin(0, 0, type);
    const std::string s = e.getStateJson(true);
    std::vector<float> out;
    const size_t p = s.find("\"params\":[");
    if (p == std::string::npos) return out;
    std::stringstream in(s.substr(p + 10, s.find(']', p) - p - 10));
    std::string v;
    while (std::getline(in, v, ',')) if (!v.empty()) out.push_back(std::stof(v));
    return out;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 2) { std::fprintf(stderr, "usage: %s <csv> [--write]\n", argv[0]); return 2; }
    const bool write = argc > 2 && std::strcmp(argv[2], "--write") == 0;

    if (write) {
        std::ofstream out(argv[1]);
        out << "# type_ordinal,param_index,default — generated by snapin_defaults_test --write\n";
        for (int t = 0; t < kTypes; t++) {
            const std::vector<float> d = nativeDefaults(t);
            for (size_t i = 0; i < d.size(); i++) out << t << ',' << i << ',' << d[i] << '\n';
        }
        std::printf("wrote %s\n", argv[1]);
        return 0;
    }

    std::map<std::pair<int, int>, float> table;
    std::ifstream in(argv[1]);
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        int t = 0, i = 0;
        float v = 0.0f;
        if (std::sscanf(line.c_str(), "%d,%d,%f", &t, &i, &v) == 3) table[{t, i}] = v;
    }
    int failures = 0;
    size_t seen = 0;
    for (int t = 0; t < kTypes; t++) {
        const std::vector<float> d = nativeDefaults(t);
        for (size_t i = 0; i < d.size(); i++, seen++) {
            auto it = table.find({t, static_cast<int>(i)});
            const float want = it == table.end() ? -12345.0f : it->second;
            const float tol = 1e-4f * (1.0f + (want < 0 ? -want : want));
            if (it == table.end() || d[i] < want - tol || d[i] > want + tol) {
                std::printf("FAIL  snapin %d param %zu: native %g, table %g\n", t, i, d[i], want);
                failures++;
            }
        }
    }
    if (seen != table.size()) {
        std::printf("FAIL  table has %zu rows, native has %zu parameters\n", table.size(), seen);
        failures++;
    }
    std::printf("%s (%zu parameters across %d snapins)\n",
                failures == 0 ? "all passed" : "FAILURES", seen, kTypes);
    return failures == 0 ? 0 : 1;
}
